s390: Fix calloc compiler error for gcc14
The definition of calloc is as follows:
    void *calloc(size_t nmemb, size_t size);
number of members is in the first parameter and the
size is in the second parameter.

Fix error message on the gcc 14 20240102:
  error: 'calloc' sizes specified with 'sizeof' in the earlier
  argument and not in the later argument ...
by adhering to the calloc() calling convention.

Output before:
 # make
 Entering directory '/root/perfmon2-libpfm4/lib'
 cc  -g -Wall -Werror -Wextra -Wno-unused-parameter -I. \
	 -I/root/perfmon2-libpfm4/lib/../include -DCONFIG_PFMLIB_DEBUG \
	 -DCONFIG_PFMLIB_OS_LINUX -DCONFIG_PFMLIB_NOTRACEPOINT \
	 -DHAS_OPENAT -D_REENTRANT -I. -fvisibility=hidden \
	 -DCONFIG_PFMLIB_ARCH_S390X -I. -c pfmlib_s390x_cpumf.c
 pfmlib_s390x_cpumf.c: In function ‘pfm_cpumcf_init’:
 pfmlib_s390x_cpumf.c:221:26: error: ‘calloc’ sizes specified with \
	 ‘sizeof’ in the earlier argument and not in the later argument \
	 [-Werror=calloc-transposed-args]
  221 | cpumcf_pe = calloc(sizeof(*cpumcf_pe), cfvn_set_count):
      |                          ^
 pfmlib_s390x_cpumf.c:221:26: note: earlier argument should specify
	number of elements, later size of each element

Signed-off-by: Thomas Richter <tmricht@linux.ibm.com>
Acked-by: Sumanth Korikkar <sumanthk@linux.ibm.com>